// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gauuiamygnvgrxovgkip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdXVpYW15Z252Z3J4b3Zna2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTkyNjAsImV4cCI6MjA4ODU5NTI2MH0.G1IKEx1la5jC_67LHbLr8x2QqJByEa0LBI8S4NVQSUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});